### PR TITLE
ProjectCard

### PR DESCRIPTION
**Pull request by autecht**
Adjusted projects classnames, new ProjectCard component, styling for project card.

### CODE REVIEW

**Comment by feydan** [comment]
Looks like a great start here.  How are you testing the display of the styles locally?  I pulled your branch and created a sample project card for OpenSac.org.  Some of the styling looks good, but some things are a bit off like the vertical spacing and the status  box.

Display when I pulled this branch
image

Figma display for reference
image

Here are the changes I added to projects.jsx to display this on the projects page
```javascript
diff --git a/src/app/projects/projects.jsx b/src/app/projects/projects.jsx
index 825ea9f..fc1e905 100644
--- a/src/app/projects/projects.jsx
+++ b/src/app/projects/projects.jsx
@@ -42,15 +42,32 @@ function fetchMdx() {
 export default function Projects() {
   const { fileContent, tableOfContents } = fetchMdx();
 
+  const tags = [{
+    id:1,
+    url:'',
+    text:'html'
+  }, {
+    id:1,
+    url:'',
+    text:'css'
+  }]
+
   return (
     <>
       <div className="projects-main">
         <ProjectsSectionStart
           sectionType={SectionType.light}
         ></ProjectsSectionStart>
-        <section className="projects-container-margins">
-          <MDXRemote source={fileContent} components={MDXComponents} />
-        </section>
+        <ProjectCard
+          sectionType={SectionType.light}
+          projectTitle='OpenSac.org'
+          projectText='Website for Open Sac'
+          imgUrl='/img/projects/opensac.jpg'
+          pageUrl=''
+          githubUrl='https://github.com/code4sac/opensac.org'
+          tags={tags}
+          lastUpdatedTimestamp='Thu Sept 21, 8:00pm'
+        ></ProjectCard>
       </div>
     </>
   );
~
```

**Comment by autecht** [comment]
I was referencing how it appeared on my computer using a different image.
Here is how it appears on my computer:
image
These are the changes to projects.jsx (no image loaded for the image url /img/projects/opensac.jpg):
```
git diff C:\Projects\OpenFresno\opensac.org\src\app\projects\projects.jsx
diff --git a/src/app/projects/projects.jsx b/src/app/projects/projects.jsx
index 825ea9f..a464ba7 100644
--- a/src/app/projects/projects.jsx
+++ b/src/app/projects/projects.jsx
@@ -41,16 +41,34 @@ function fetchMdx() {
  */
 export default function Projects() {
   const { fileContent, tableOfContents } = fetchMdx();
-
+  const tags = [
+    {
+      id: 1,
+      url: "",
+      text: "html",
+    },
+    {
+      id: 1,
+      url: "",
+      text: "css",
+    },
+  ];
   return (
     <>
       <div className="projects-main">
         <ProjectsSectionStart
           sectionType={SectionType.light}
         ></ProjectsSectionStart>
-        <section className="projects-container-margins">
-          <MDXRemote source={fileContent} components={MDXComponents} />
-        </section>
+        <ProjectCard
+          sectionType={SectionType.light}
+          projectTitle="OpenSac.org"
+          projectText="Website for Open Sac"
+          imgUrl="/img/towerbridgenight.png"
+          pageUrl=""
+          githubUrl="https://github.com/code4sac/opensac.org"
+          tags={tags}
+          lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+        ></ProjectCard>
       </div>
     </>
   );
```

I'll work on more consistent and accurate spacing and sizing.

**Comment by autecht** [comment]
Here is what the styling looks like with example projects: 
image


Here are the changes to display the above:
```
diff --git a/src/app/projects/projects.jsx b/src/app/projects/projects.jsx
index 0d936e1..245805b 100644
--- a/src/app/projects/projects.jsx
+++ b/src/app/projects/projects.jsx
@@ -1,6 +1,6 @@
 "use client";
 import ProjectsSectionStart from "@/app/projects/projectsSectionStart";
-import ProjectCard from "@/app/projects/projectCard"
+import ProjectCard from "@/app/projects/projectCard";
 import { fetchJson } from "@/utils/fetcher";
 import useSWR from "swr";
 import * as yaml from "yaml";
@@ -35,7 +35,57 @@ export default function Projects() {
         <ProjectsSectionStart
           sectionType={SectionType.light}
         ></ProjectsSectionStart>
-        <div className = "project-cards-container">
+        <div className="project-cards-container">
+          <ProjectCard
+            sectionType={SectionType.light}
+            projectTitle="OpenSac.org"
+            projectText="Website for Open Sac"
+            imgUrl="/img/about/towerbridgeside.png"
+            pageUrl=""
+            githubUrl="https://github.com/code4sac/opensac.org"
+            tags={["html", "html"]}
+            lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+          ></ProjectCard>
+          <ProjectCard
+            sectionType={SectionType.light}
+            projectTitle="OpenSac.org"
+            projectText="Website for Open Sac"
+            imgUrl="/img/projects/opensac.png"
+            pageUrl=""
+            githubUrl="https://github.com/code4sac/opensac.org"
+            tags={["html", "html"]}
+            lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+          ></ProjectCard>
+          <ProjectCard
+            sectionType={SectionType.light}
+            projectTitle="OpenSac.org"
+            projectText="Website for Open Sac"
+            imgUrl="/img/about/towerbridgeside.png"
+            pageUrl=""
+            githubUrl="https://github.com/code4sac/opensac.org"
+            tags={["html", "html"]}
+            lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+          ></ProjectCard>
+          <ProjectCard
+            sectionType={SectionType.light}
+            projectTitle="OpenSac.org"
+            projectText="Website for Open Sac"
+            imgUrl="/img/projects/opensac.png"
+            pageUrl=""
+            githubUrl="https://github.com/code4sac/opensac.org"
+            tags={["html", "html"]}
+            lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+          ></ProjectCard>
+          <ProjectCard
+            sectionType={SectionType.light}
+            projectTitle="OpenSac.org"
+            projectText="Website for Open Sac"
+            imgUrl="/img/about/towerbridgeside.png"
+            pageUrl=""
+            githubUrl="https://github.com/code4sac/opensac.org"
+            tags={["html", "html"]}
+            lastUpdatedTimestamp="Thu Sept 21, 8:00pm"
+          ></ProjectCard>
         </div>
       </div>
     </>
(END)
```

**Review by natebass — APPROVED** [review]
Merging. It matches the Figma design.

Thank you @autecht @feydan.

**Pull request merged**
